[ss13tools]
api_url = "https://api.paradisestation.org"
working_directory = "D:/ExternalRepos/ss13_blackbox_tools"
log_tasks = true
paradise_root = "D:/ExternalRepos/third_party/Paradise"
connection_string = "mysql+mysqldb://root@localhost/parastats_prod"
profile_proc_paths = [
    "/datum/controller/subsystem/atoms/proc/InitializeAtoms",
    "/datum/controller/subsystem/mapping/proc/loadLavaland",
    "/datum/controller/subsystem/mapping/proc/loadStation",
    "/turf/simulated/mineral/random/Initialize",
]
